name: Build & Deploy backend to tomcat server

on:
  push:
    branches:
      - main1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Build WAR File
        run: mvn clean package -Dspring.profiles.active=prod -DskipTests

      - name: Backup existing WAR on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            NOW=$(date +"%Y-%m-%dT%H-%M-%S")
            BACKUP_DIR="${{ secrets.TOMCAT_FOLDER }}/webapps/oxysystem_grab_backup"
            FILE_PATH="${{ secrets.TOMCAT_FOLDER }}/webapps/oxysystem-backend-staging.war"
            
            mkdir -p "$BACKUP_DIR"

            if [ -f "$FILE_PATH" ]; then
              cp "$FILE_PATH" "$BACKUP_DIR/oxysystem-backend-staging_$NOW.war"
              echo "Backup created: oxysystem-backend-staging_$NOW.war"
            else
              echo "No existing WAR to backup"
            fi

      - name: Copy new WAR to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "target/oxysystem-backend-staging.war"
          target: ${{ secrets.TOMCAT_FOLDER }}/webapps/
          strip_components: 1